---
- name: Compile speex (libtoolize)
  command: libtoolize --force
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_speex_repo_dir }}"

- name: Compile speex (aclocal)
  command: aclocal
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_speex_repo_dir }}"

- name: Compile speex (autoheader)
  command: autoheader
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_speex_repo_dir }}"

- name: Compile speex (automake)
  command: automake --force-missing --add-missing
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_speex_repo_dir }}"

- name: Compile speex (autoconf)
  command: autoconf -i
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_speex_repo_dir }}"

- name: Compile speex (configure)
  command: ./configure --prefix={{ ffmpeg_build_dir }} --disable-shared
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_speex_repo_dir }}"

- name: Compile speex (make)
  command: make
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_speex_repo_dir }}"

- name: Compile speex (make install)
  command: make install
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_speex_repo_dir }}"

- name: Compile speex (make distclean)
  command: make distclean
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_speex_repo_dir }}"