---
- name: Compile libfdkaac (autoreconf)
  command: autoreconf -fiv
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_libfdkaac_repo_dir }}"

- name: Compile libfdkaac (configure)
  command: ./configure --prefix="{{ ffmpeg_build_dir }}" --disable-shared
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_libfdkaac_repo_dir }}"

- name: Compile libfdkaac (make)
  command: make
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_libfdkaac_repo_dir }}"

- name: Compile libfdkaac (make install)
  command: make install
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_libfdkaac_repo_dir }}"

- name: Compile libfdkaac (make distclean)
  command: make distclean
  args:
      chdir: "{{ ffmpeg_source_dir }}/{{ ffmpeg_libfdkaac_repo_dir }}"